### ISSUE TITLE
Babel error when running typescript example

### ISSUE THREAD

**Issue by DiscoDancer** [gaearon/react-hot-loader#1025]
### Description
Hello, I have an issue with running _typescript_ example.

What you are reporting:
Fail while building example

### Expected behavior
webpack server runs successfully 

### Actual behavior

What actually happens:
```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of
 this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (C:\Users\vlev\Desktop\a1\react-hot-loader\examples\typescript\node_modules\@babel\helper-plugin-utils\lib\index.js:65:11)
    at Object.assertVersion (C:\Users\vlev\Desktop\a1\react-hot-loader\examples\typescript\node_modules\@babel\helper-plugin-utils\lib\index.js:13:11)
    at _default (C:\Users\vlev\Desktop\a1\react-hot-loader\examples\typescript\node_modules\@babel\plugin-syntax-typescript\lib\index.js:36:7)
    at C:\Users\vlev\Desktop\a1\react-hot-loader\examples\typescript\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at Function.memoisePluginContainer (C:\Users\vlev\Desktop\node_modules\babel-core\lib\transformation\file\options\option-manager.js:113:13)
    at Function.normalisePlugin (C:\Users\vlev\Desktop\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
    at C:\Users\vlev\Desktop\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\vlev\Desktop\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\vlev\Desktop\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\vlev\Desktop\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\vlev\Desktop\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\vlev\Desktop\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\vlev\Desktop\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireConfig (C:\Users\vlev\Desktop\a1\react-hot-loader\examples\typescript\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\Users\vlev\Desktop\a1\react-hot-loader\examples\typescript\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\vlev\Desktop\a1\react-hot-loader\examples\typescript\node_modules\webpack\bin\convert-argv.js:102:15)
    at Object.<anonymous> (C:\Users\vlev\Desktop\a1\react-hot-loader\examples\typescript\node_modules\webpack-dev-server\bin\webpack-dev-server.js:223:50)
    at Module._compile (module.js:652:30)
```
### Environment

React Hot Loader version:
^4.1.2 (same as in repository)

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.11.3
2.  `npm -v`: 6.1.0

Then, specify:

1.  Operating system: Windows 10 x64
2.  Browser and version: console output

### Reproducible Demo

1. clone repository
2. 
```
cd \examples\typescript
```

3. 
```
npm install
```
4.
```
npm start
```

**Comment by DiscoDancer** [comment]
upd: fixed by removing all `^` in `package.json`

**Comment by theKashey** [comment]
Hey! Could you send a PR to fix it in our repo?

**Comment by DiscoDancer** [comment]
@theKashey Hi, I can do. I now know better solution, since last change of @types/react in ts example constructor should be changed. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26898

**Comment by DiscoDancer** [comment]
Completely deleted NodeJS and npm (including removing all caches and global packages), then installed the latest stable NodeJS and manually updated npm to the latest.

And now it works with no issues.
