### ISSUE TITLE
Parcel Example is broken

### ISSUE THREAD

**Issue by andrew-w-ross** [gaearon/react-hot-loader#1191]
### Description

Bug with parcel example, also it seems to be really out of date.

### Expected behavior

Parcel example should work

### Actual behavior

```
Server running at http://localhost:1234 
🚨  /home/andrewross/Projects/react-hot-loader/examples/parcel/src/index.js: Unknown version 11.3 of ios_saf
    at Function.select (/home/andrewross/Projects/react-hot-loader/examples/parcel/node_modules/babel-preset-env/node_modules/browserslist/index.js:793:17)
    at /home/andrewross/Projects/react-hot-loader/examples/parcel/node_modules/babel-preset-env/node_modules/browserslist/index.js:181:33
    at Array.reduce (<anonymous>)
    at resolve (/home/andrewross/Projects/react-hot-loader/examples/parcel/node_modules/babel-preset-env/node_modules/browserslist/index.js:162:18)
    at browserslist (/home/andrewross/Projects/react-hot-loader/examples/parcel/node_modules/babel-preset-env/node_modules/browserslist/index.js:272:16)
    at getTargets (/home/andrewross/Projects/react-hot-loader/examples/parcel/node_modules/babel-preset-env/lib/targets-parser.js:103:63)
    at Object.buildPreset [as default] (/home/andrewross/Projects/react-hot-loader/examples/parcel/node_modules/babel-preset-env/lib/index.js:144:45)
    at getEnvPlugins (/home/andrewross/Projects/react-hot-loader/examples/parcel/node_modules/parcel-bundler/src/transforms/babel.js:263:34)
    at getEnvConfig (/home/andrewross/Projects/react-hot-loader/examples/parcel/node_modules/parcel-bundler/src/transforms/babel.js:230:25)
```

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1.  `node -v`: v11.9.0
2.  `npm -v`: v6.5.0

Then, specify:

1.  Operating system: Ubuntu 18.10
2.  Browser and version: Chrome 72.0.3626.119

### Reproducible Demo

It's the parcel example in this repo

**Comment by theKashey** [comment]
browserlist has to be updated.

**Comment by tlrobinson** [comment]
Is Parcel support completely broken, or just the example? Is there a known working version?

**Comment by tlrobinson** [comment]
FYI the latest version I found where the Parcel example works is v4.2.0.
