### ISSUE TITLE
webpack build error when aliasing react-dom

### ISSUE THREAD

**Issue by wmertens** [gaearon/react-hot-loader#1243]
### Description

When I configure Webpack to use the documented approach to alias `react-dom` to `@hot-loader/react-dom`, the build fails with the error

```
ModuleBuildError: Module build failed (from ./node_modules/.registry.npmjs.org/react-hot-loader/4.8.4/node_modules/react-hot-loader/webpack.js):
TypeError: Cannot read property 'indexOf' of undefined
    at Object.transform$1 (/project/node_modules/.registry.npmjs.org/react-hot-loader/4.8.4/node_modules/react-hot-loader/dist/webpack.development.js:118:14)
    at runLoaders (/project/node_modules/.registry.npmjs.org/webpack/4.30.0/node_modules/webpack/lib/NormalModule.js:301:20)
    at /project/node_modules/.registry.npmjs.org/loader-runner/2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/.registry.npmjs.org/loader-runner/2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/project/node_modules/.registry.npmjs.org/loader-runner/2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/project/node_modules/.registry.npmjs.org/loader-runner/2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/project/node_modules/.registry.npmjs.org/loader-runner/2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/project/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/project/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /project/node_modules/.registry.npmjs.org/graceful-fs/4.1.15/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

No idea how this is possible, but there it is. When I remove the alias entry from the configuration, it builds just fine.

### Environment

React Hot Loader version: 4.8.4

```
$ node -v
v10.15.3
$ pnpm -v
3.0.0
```
Then, specify:

1.  Operating system: macOS
2.  Browser and version: N/A

### Reproducible Demo

It will take me quite some time to build a repro, so I'm hoping it won't be necessary. If not, I'll build one.

**Comment by theKashey** [comment]
Dup  #1234.
