### ISSUE TITLE
TypeError: Property value expected type of string but got null (NODE_ENV not set)

### ISSUE THREAD

**Issue by cblanquera** [gaearon/react-hot-loader#1352]
I tried looking through the open and closed issues before posting this. Thanks for reading.

### Description

Error shown in terminal when adding `react-hot-loader/babel` in `.babelrc and the computer's `NODE_ENV` is not set. *( Will happen on a new computer :D )*

### Expected behavior

Since most node libraries test for `NODE_ENV` to be `production` to perform production related activities, we can safely assume that the default environment is `development`? *(Feel free to correct my logic)*

But if undecided, then maybe at least log to the developer that their environment is not set and should set it to `development`

### Actual behavior

My `NODE_ENV` was not set and got the error as the title describes when running my app in terminal.

### Environment

React Hot Loader version: **4.12.14**

Run these commands in the project folder and fill in their results:

1.  `node -v`: **v12.10.0**
2.  `npm -v`: **6.11.3**

Then, specify:

1.  Operating system: **macOS Mojave**
2.  Browser and version: **happens in terminal not browser**

### Reproducible Demo

Use a basic project with `react-hot-loader` installed. Make sure you include `react-hot-loader/babel` in `.babelrc` like the following.

.babelrc
```.json
{
  "plugins": ["react-hot-loader/babel"],
  "presets": ["@babel/env", "@babel/preset-react"]
}
```

In terminal unset your node environment by:

```bash
$ unset NODE_ENV
```

Then start up your project. `npm start` maybe ?

```bash
babel-node test/env-1/src/index.js

webpack built e7cdbc390e5bffef4259 in 2045ms
ℹ ｢wdm｣: Hash: e7cdbc390e5bffef4259
Version: webpack 4.41.0
Time: 2045ms
Built at: 10/04/2019 6:39:50 PM
          Asset      Size  Chunks             Chunk Names
    0.bundle.js  5.19 KiB       0  [emitted]  
    1.bundle.js  5.47 KiB       1  [emitted]  
index.bundle.js  2.81 MiB   index  [emitted]  index
Entrypoint index = index.bundle.js
[0] multi webpack-hot-middleware/client?reload=true reactus/entry.js 40 bytes {index} [built]
[./node_modules/@babel/polyfill/lib/index.js] 686 bytes {index} [built]
[./node_modules/@babel/polyfill/lib/noConflict.js] 567 bytes {index} [built]
[./node_modules/@babel/runtime/helpers/esm/extends.js] 397 bytes {index} [built]
[./node_modules/@hot-loader/react-dom/index.js] 1.33 KiB {index} [built]
[./node_modules/history/esm/history.js] 28.1 KiB {index} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {index} [built]
[./node_modules/reactus/Router.jsx] 9.71 KiB {index} [built]
[./node_modules/reactus/entry.js] 417 bytes {index} [built]
[./node_modules/reactus/routes.js] 71 bytes {index} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {index} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.17 KiB {index} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true] (webpack)-hot-middleware/client.js?reload=true 7.68 KiB {index} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.35 KiB {index} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {index} [built]
    + 354 hidden modules
ℹ ｢wdm｣: Compiled successfully.
(node:38145) UnhandledPromiseRejectionWarning: TypeError: Property value expected type of string but got null
    at Object.validate (/server/node/demo-ssr-project/node_modules/@babel/types/lib/definitions/utils.js:164:13)
    at validateField (/server/node/demo-ssr-project/node_modules/@babel/types/lib/validators/validate.js:22:9)
    at validate (/server/node/demo-ssr-project/node_modules/@babel/types/lib/validators/validate.js:16:3)
    at builder (/server/node/demo-ssr-project/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.StringLiteral (/server/node/demo-ssr-project/node_modules/@babel/types/lib/builders/generated/index.js:337:31)
    at enter (/server/node/demo-ssr-project/node_modules/react-hot-loader/dist/babel.development.js:603:29)
    at sourceRecord.<computed> (/server/node/demo-ssr-project/node_modules/react-hot-loader/dist/babel.development.js:686:16)
    at PluginPass.sourceRecord.<computed> (/server/node/demo-ssr-project/node_modules/react-hot-loader/dist/babel.development.js:685:14)
    at newFn (/server/node/demo-ssr-project/node_modules/@babel/traverse/lib/visitors.js:195:21)
    at NodePath._call (/server/node/demo-ssr-project/node_modules/@babel/traverse/lib/path/context.js:53:20)
(node:38145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> NOTE: For everyone else reading this you can set your `NODE_ENV` back by running the following command

```bash
$ export NODE_ENV=development
```

**Comment by cblanquera** [comment]
For anyone that has this same issue, it is because your `NODE_ENV` is not set. You can set it in your terminal by running the following.

```bash
$ export NODE_ENV=development
```
