### ISSUE TITLE
Babel cannot transform

### ISSUE THREAD

**Issue by willin** [gaearon/react-hot-loader#264]
```
babel app.js -o app.out.js
```

```
Error: Cannot find module 'css!./style.css'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/willin/Documents/wulian/v3/bash/dev/app/modules/App.js:15:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

```js
import React from 'react';
import NavLink from './NavLink';
require('css!./style.css');  // <-- Error Here
export default React.createClass({
  render() {
    return (
      <div>
        <h1>React Router Tutorial</h1>
        <ul role="nav">
          <li><NavLink to="/" onlyActiveOnIndex>Home</NavLink></li>
          <li><NavLink to="/about">About</NavLink></li>
          <li><NavLink to="/repos">Repos</NavLink></li>
        </ul>
        {this.props.children}
      </div>
    );
  }
});
```

**Comment by adam-beck** [comment]
@willin are you sure this is a react-hot-loader issue? To me, it looks like a configuration error inside of your project. Could you point to the repo and I can help?

**Comment by willin** [comment]
config:


```js
var webpack = require('webpack')
var path = require('path')

module.exports = {
  devtool: 'eval',
  entry: [
    'webpack-dev-server/client?http://localhost:5889',
    'webpack/hot/only-dev-server',
    path.join(__dirname,'src/app','index.js')
  ],
  output: {
    path: path.join(__dirname, '/.deploy/public'),
    publicPath: '//127.0.0.1:5889/static/',
    filename: 'app.bundle.js'
  },

  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false }
    }),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify(process.env.NODE_ENV)
      }
    }),
    new webpack.HotModuleReplacementPlugin()
  ],

  module: {
    loaders: [
      { test: /\.jsx?$/, exclude: /node_modules/, loaders: ['react-hot','babel-loader?presets[]=es2015-loose&presets[]=react&presets[]=stage-1&plugins[]=transform-runtime'] },
      // { test: /\.jsx?$/, loaders: ['react-hot', 'jsx?harmony'], include: path.join(__dirname) },
      {test: /\.css$/, loader: 'style!css'},
      {test: /\.scss$/, loader: 'style!css!sass'},
      { test: /\.less$/, loader: 'style!css!less' },
      { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=8192|file?name=static/[name].[ext]' },
      { test: /\.(jpeg|jpg|woff|woff2|eot|ttf|svg)(\?.*$|$)/, loader: "file?name=static/[name].[ext]" }
    ]
  },

  // Automatically transform files with these extensions
  resolve: {
    extensions: ['', '.js', '.jsx', '.css']
  },
  // Additional plugins for CSS post processing using postcss-loader
  postcss: [
    require('autoprefixer'), // Automatically include vendor prefixes
    require('postcss-nested') // Enable nested rules, like in Sass
  ]
}
```


dev-server:

```js
// require('babel/polyfill');

import webpack from 'webpack';
import WebpackDevServer from 'webpack-dev-server';
import config from '../../webpack.config.dev';

new WebpackDevServer(webpack(config), {
  publicPath: config.output.publicPath,
  hot: true,
  historyApiFallback: true,
  stats: {
    colors: true
  }
}).listen(5889, '127.0.0.1', (err) => {
  if (err) { console.log(err); }
  console.log('Webpack listening at 5889');
});
```

green hand in react, sorry

**Comment by adam-beck** [comment]
Try `require('./style.css')` or `import './style.css`. You are already configuring the loaders in your webpack configuration file.

**Comment by gaearon** [comment]
Hi! I don’t see how this is related to React Hot Loader so I’m closing. This is an issue tracker of React Hot Loader.

If you can show that it is React Hot Loader that’s causing this issue, I’m happy to reopen, but so far I see no sign of that.
