### ISSUE TITLE
ES6 compilation error in react-hot-loader@^1.1.4

### ISSUE THREAD

**Issue by doctyper** [gaearon/react-hot-loader#76]
Running `react-hot-loader@^1.1.4` I am seeing the following error attempting to run webpack with the hot-loader:

```
ERROR in ./main.jsx
Module build failed: SyntaxError: example/main.jsx: 'import' and 'export' may only appear at the top level (3:0)
  1  | /* REACT HOT LOADER */ if (module.hot) { (function () { var ReactHotAPI = require("node_modules/react-hot-loader/node_modules/react-hot-api/modules/index.js"), RootInstanceProvider = require("node_modules/react-hot-loader/RootInstanceProvider.js"), ReactMount = require("react/lib/ReactMount"); module.makeHot = module.hot.data ? module.hot.data.makeHot : ReactHotAPI(function () { return RootInstanceProvider.getRootInstances(ReactMount); }); })(); } (function () {
  2  | 
> 3  | import {main} from "src/index";
     | ^
  4  | import ApplicationRoutes from "./src/routes/ApplicationRoutes";
  5  | 
  6  | export default main({
    at raise (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:343:15)
    at parseStatement (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:2597:9)
    at parseBlock (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:2884:18)
    at parseFunctionBody (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3572:19)
    at parseFunction (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3519:5)
    at parseExprAtom (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3249:14)
    at parseExprSubscripts (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3096:16)
    at parseMaybeUnary (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3078:16)
    at parseExprOps (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3032:16)
    at parseMaybeConditional (node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3008:16)
 @ multi main
```

The error goes away when using `react-hot-loader@1.1.3`. ([Diff](https://github.com/gaearon/react-hot-loader/compare/v1.1.3...master))

**Comment by gaearon** [comment]
What's your Webpack config? `react-hot` transform should be done after `6to5`, so loaders config should look like `['react-hot', '6to5`]` (yeah, I don't know why it's right to left lol).

Does this help?

**Comment by doctyper** [comment]
Ah! That was it, thanks. Not sure how it was working before?

**Comment by gaearon** [comment]
I just added wrapping user code in IIFE to preserve "use strict" if user had it. So it worked as is before IIFE but wouldn't now.
